# Stage 1: install & build
FROM node:20-alpine AS builder
WORKDIR /Skyight-B2C

# install dependencies
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# copy source and build
COPY . .
RUN npm run build      # this creates .next

# Stage 2: production image
FROM node:20-alpine AS runner
WORKDIR /Skyight-B2C

# copy build outputs and deps
COPY --from=builder /Skyight-B2C/.next ./.next
COPY --from=builder /Skyight-B2C/node_modules ./node_modules
COPY --from=builder /Skyight-B2C/package.json ./

# expose and start
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npx", "next", "start"]