# Stage 1: build & export
FROM node:20-alpine AS builder
WORKDIR /Skyight-B2C

# install deps
COPY package*.json ./
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm ci --legacy-peer-deps

# copy source & build
COPY . .
RUN npm run build
RUN npm run export   # <-- produces /Skyight-B2C/out

# Stage 2: serve static with nginx
FROM nginx:alpine
# remove default content
RUN rm -rf /usr/share/nginx/html/*
# copy your export
COPY --from=builder /Skyight-B2C/out /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
